language: ruby
rvm:
  - 2.4.1

env:
  global:
    - DUMMY=foo

install:
  - bundle install

script:
  - cd ./docs
  - JEKYLL_ENV=production bundle exec jekyll build

deploy:
  - echo "SUCCESS"

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

exclude: [vendor]

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
